dist: "bionic"
language: cpp

# Handle git submodules yourself
git:
    submodules: false

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libgtest-dev
      - libeigen3-dev
    update: true

before_install:
  - sudo apt update
  - sudo apt install -y libgtest-dev libeigen3-dev cmake build-essential
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - gcc --version

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - ./geometry_test

